//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirestbeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_APPOINTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_APPOINTMENT()
        {
            this.TBL_EMPLOYEE = new HashSet<TBL_EMPLOYEE>();
        }
    
        public int AppointmentId { get; set; }
        public string AppointmentName { get; set; }
        public string AppointmentDescription { get; set; }
        public int AreaId { get; set; }
        public int AppointmentState { get; set; }
    
        public virtual TBL_AREA TBL_AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_EMPLOYEE> TBL_EMPLOYEE { get; set; }
    }
}
