//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apirestbeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_AREA()
        {
            this.TBL_APPOINTMENT = new HashSet<TBL_APPOINTMENT>();
        }
    
        public int AreaId { get; set; }
        public string AreaName { get; set; }
        public string AreaDescription { get; set; }
        public int AreaState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_APPOINTMENT> TBL_APPOINTMENT { get; set; }
    }
}
